name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: 0 0 * * 1-5
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ !contains(github.ref, 'main')}}"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  clippy:
    name: "Rust clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add clippy
      - run: cargo clippy --verbose --tests --all-targets --all-features -- -D warnings

  formatter:
    name: "Rust formatter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo fmt --check --verbose

  cross_compile:
    name: "Cross compile"
    uses: ./.github/workflows/build_release.yaml
    with:
      branch: "${{ github.head_ref || github.ref_name }}"
      upload_artifacts: false
      run_versioning: false
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.PUBLISH_DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.PUBLISH_DOCKERHUB_TOKEN}}
